version: 1.2.{build}
image: Visual Studio 2017
before_build:
- ps: dotnet restore src
configuration:
  - Debug
  - Release
build:
  publish_nuget: true
  verbosity: minimal
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: $(appveyor_build_version)
deploy:
- provider: NuGet
  api_key:
    secure: I4D2if8a4z4v+GbcoydJ4T2U2H5ymglpv6kpQjSQ2qxPKj73ZFjOxR+N77y3urLy
  on:
    branch: master
    configuration: Release
