version: 1.0.{build}
image: Previous Visual Studio 2017
before_build:
- ps: >-
    cd source

    dotnet restore
build:
  project: source/kasthack.yandex.pdd.csproj
  publish_nuget: true
  verbosity: minimal
deploy:
- provider: NuGet
  api_key:
    secure: I4D2if8a4z4v+GbcoydJ4T2U2H5ymglpv6kpQjSQ2qxPKj73ZFjOxR+N77y3urLy
